[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "majia"
version = "0.1.0"
description = "Simple CLI tool to render Mako/Jinja2 templates"
authors = [
  { name="Andrea Di Ruzza" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "Mako"
]

[project.scripts]
majia = "majia.cli:main"
